# Example:
# production:
#   adapter: mysql
#   encoding: utf8
#   database: [database name]
#   username: [user name]
#   password: [password]
#   host: [server IP address]
#   port: [port number]
#   protocol: [protocol]
#   pool: [connection pool]

development:
  adapter: mysql
  encoding: utf8
  database: agrupamento56
  username: root
  password: ''
  host: 127.0.0.1
  port: 3306
  pool: 10

# production:
#   adapter: mysql
#   encoding: utf8
#   database: rails_myapp
#   username: rails_myapp_user
#   password: pwd
#   host: 128.199.233.36
#   port: 3306
#   pool: 10